from enum import Enum


class State(Enum):
    STATE_SOUND_NEW = 1
    STATE_SOUND_AVAILABLE = 2
    STATE_CONVERSE_NEW = 3
    STATE_CONVERSE_AVAILABLE = 4
    STATE_SOUND_NEW = 5
    STATE_CONVERSE_NEW = 6
    STATE_SOUND_AVAILABLE = 7
    STATE_CONVERSE_AVAILABLE = 8
