class State():
    STATE_IDLE = 0
    STATE_DETECTED = 1
    STATE_NOT_DETECTED = 2
    STATE_WAITING_FOR_CONFIRMATION = 3
    STATE_CONFIRMATION_NO = 4
    STATE_CONFIRMATION_YES = 5
    STATE_SOUND_NEW = 6
    STATE_SOUND_AVAILABLE = 7
    STATE_CONVERSE_NEW = 8
    STATE_CONVERSE_AVAILABLE = 9
    STATE_SOUND_NEW = 10
    STATE_CONVERSE_NEW = 11
    STATE_SOUND_AVAILABLE = 12
    STATE_CONVERSE_AVAILABLE = 13
