import os


class Dir():
    BASE = os.getcwd()
    TMP = BASE + '/tmp/'
    DATA = BASE + '/data/'
    PICTURES = DATA + 'pictures/'


class State():
    STATE_FACE_NOBODY = -2
    STATE_FACE_NOBODY_AVAILABLE = -3
    STATE_FACE_UNKNOWN = -1
    STATE_FACE_KNOWN = 0
    STATE_FACE_KNOWN_AVAILABLE = 1
    STATE_FACE_UNKNOWN_AVAILABLE = 2
    STATE_FACE_MULTIPLES = 3
    STATE_FACE_MULTIPLES_AVAILABLE = 4
    STATE_FACE_WORKING = 5
    STATE_FACE_NOT_WORKING = 6
    STATE_SOUND_NEW = 6
    STATE_SOUND_AVAILABLE = 7
    STATE_CONVERSE_NEW = 8
    STATE_CONVERSE_AVAILABLE = 9
    STATE_SOUND_NEW = 10
    STATE_CONVERSE_NEW = 11
    STATE_SOUND_AVAILABLE = 12
    STATE_CONVERSE_AVAILABLE = 13
    STATE_EMOTION_NEW = 15
    STATE_EMOTION_NO = 16
    STATE_KEYBOARD_NEW = 17
    STATE_KEYBOARD_AVAILABLE = 18
