import os


class Dir():
    BASE = os.getcwd()
    TMP = BASE + '/tmp/'
    DATA = BASE + '/data/'
    PICTURES = DATA + 'pictures/'


class State():
    STATE_FACE_NOBODY = -2
    STATE_FACE_NOBODY_AVAILABLE = -3
    STATE_FACE_UNKNOWN = -1
    STATE_FACE_KNOWN = 0
    STATE_FACE_KNOWN_AVAILABLE = 1
    STATE_FACE_UNKNOWN_AVAILABLE = 2
    STATE_WAITING_FOR_CONFIRMATION = 3
    STATE_SOUND_NEW = 6
    STATE_SOUND_AVAILABLE = 7
    STATE_CONVERSE_NEW = 8
    STATE_CONVERSE_AVAILABLE = 9
    STATE_SOUND_NEW = 10
    STATE_CONVERSE_NEW = 11
    STATE_SOUND_AVAILABLE = 12
    STATE_CONVERSE_AVAILABLE = 13
    STATE_EMOTION_NEW = 14
    STATE_EMOTION_NO = 13
